branches:
  only:
  - master
  - stable

# Test push
matrix:
    include:
      - os: linux
        dist: xenial   
     
language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - pip install codecov
  - pip install pytest-cov

  - pip install .

script:
  - pytest --cov=./
  
after_success:
  - codecov # submit coverage
  - bash <(curl -s https://codecov.io/bash)
