# Test push
matrix:
    include:
      - os: linux
        dist: xenial   
        
language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - pip install codecov
  - pip install .

script:
  - pytest
  
after_success:
  - codecov # submit coverage
