# Test push
matrix:
    include:
      - os: linux
        dist: xenial   
      - os: osx
        
language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - pip install .

script:
  - pytest
